version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: tutum/hello-world:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:

